<!--
	Invalid certificate:
		blaze.pydata.org
		blz.pydata.org
		chicago.pydata.org
		compilers.pydata.org
		datashape.pydata.org
		llvmlite.pydata.org
		odo.pydata.org
		xarray.pydata.org

	No working URL known:
		cdn.pydata.org

	Refused:
		conda-test.pydata.org

-->
<ruleset name="Python Data">

	<target host="pydata.org" />
	<target host="www.pydata.org" />
	<target host="berlin.pydata.org" />
	<target host="bokeh.pydata.org" />
	<target host="conda.pydata.org" />
	<target host="dask.pydata.org" />
	<target host="london.pydata.org" />
	<target host="numba.pydata.org" />
	<target host="pandas.pydata.org" />
	<target host="seaborn.pydata.org" />

	<securecookie host=".+" name=".+" />

	<rule from="^http:" to="https:" />

</ruleset>
