<!--
	Invalid certificate:
		llvmlite.pydata.org
		odo.pydata.org

	No working URL known:
		cdn.pydata.org

	Refused:
		conda-test.pydata.org

-->
<ruleset name="Python Data">

	<target host="pydata.org" />
	<target host="www.pydata.org" />
	<target host="berlin.pydata.org" />
	<target host="blaze.pydata.org" />
	<target host="blz.pydata.org" />
	<target host="bokeh.pydata.org" />
	<target host="chicago.pydata.org" />
	<target host="compilers.pydata.org" />
	<target host="conda.pydata.org" />
	<target host="dask.pydata.org" />
	<target host="datashape.pydata.org" />
	<target host="london.pydata.org" />
	<target host="numba.pydata.org" />
	<target host="pandas.pydata.org" />
	<target host="seaborn.pydata.org" />
	<target host="xarray.pydata.org" />
	
	<securecookie host=".+" name=".+" />

	<rule from="^http:" to="https:" />

</ruleset>
